### ISSUE TITLE
"git push --dry-run" shouldn't trigger "Apprentice Socialite"

### ISSUE THREAD

**Issue by dbarnett** [icefox/git-achievements#22]
> ```
>                     Apprentice Socialite (Level 1)                        
>          pushed a branch to a remote repository using git push            
> ```

The message implies I've pushed when in fact I have not. It actually made me concerned that I had accidentally pushed instead of doing a dry run.

**Comment by templeman** [comment]
This was resolved in b8e18b5. Thanks @dbarnett!
