### ISSUE TITLE
All links to kernel.org/pub/software/scm/git/... are broken

### ISSUE THREAD

**Issue by JamesFerguson** [icefox/git-achievements#53]
Seems the git man pages have moved to http://schacon.github.com/git/git-add.html etc. The main git homepage is now http://git-scm.com/documentation.

I run a link checker on my blog which includes my git-achievements and it picked up all these links being broken.

You should be able to reproduce this by clicking on any of the git command links on http://icefox.github.com/git-achievements/

**Comment by jalcine** [comment]
Might wanna close this since it's all fixed up :wink:

**Comment by templeman** [comment]
The kernel.org links seem to be working fine these days.
